loglevel: INFO

paths:
  # Path to directory containing all proxy media
  proxy_path_root: R:/ProxyMedia

proxy_settings:
  ffmpeg_loglevel: error # Set to "verbose" to see FFMPEG output
  vid_codec: dnxhd
  h_res: 1280 
  v_res: 720
  vid_profile: dnxhr_sq 
  pix_fmt: yuv422p
  audio_codec: pcm_s16le
  audio_samplerate: 48000
  misc_args: [-hide_banner, -stats]
  ext: .mxf

filters:
  # Necessary to prevent queueing internally generated media
  extension_whitelist : [.mov, .mp4, .mxf, .avi]
  use_framerate_whitelist: false
  framerate_whitelist : [24, 25, 30, 50, 60]

celery_settings:

  host_address: 192.168.1.19
  broker_url:  redis://192.168.1.19:6379/0
  flower_url: http://192.168.1.19:5555
  result_backend: redis://192.168.1.19:6379/0

  result_expires: 60 # 10 mins

  worker_loglevel: INFO
  worker_concurrency: 1
  worker_prefetch_multiplier: 1
  worker_max_tasks_per_child: 1
  worker_use_win_terminal: True
  worker_start_minimized: True
  