name: Update Version Constraint Key

on: push

jobs:

  update-vc-key:

    runs-on: [ubuntu-latest]

    steps:

      - name: Install petname
        shell: bash
        run: |
          sudo apt update
          sudo apt install petname -y

      - name: Generate name
        shell: bash
        run: |
          echo "petname=$(petname --words 3 --complexity 0 --ubuntu)" >> $GITHUB_ENV

      - name: Check result
        shell: bash
        run: |
          echo New version constraint key: ${{ env.petname }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Write VC key file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: src/version_constraint_key
          contents: |
            ${{ env.petname }}
          write-mode: overwrite

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "refactor: Update version_constraint_key"